---
azure_storage_conn_str: "DefaultEndpointsProtocol=https;AccountName=azsvkstore;AccountKey=yVi1Bj/Fd2nH8WbqbyU5ME2TB0akiHpp/0gel0cECmxbLKNUyINj1wCyE/lQQO6sn023UojI3wow+XUK/GRddw==;EndpointSuffix=core.windows.net"
container_name: "az-data"
auth_url: "https://login.microsoftonline.com/{tenantID}/oauth2/token?api-version=1.0"
restart_url: "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/restart?api-version=2021-02-01"
tenant_id: "ce75279f-1cad-43e8-bda2-a6f00ae8b804"
client_id: "d676d218-d1bf-4b0a-9a21-fab04f28c3d2"
client_secret: "YF_7Q~75j4H8nXj2_UOyfn6tMuf2Ku8~0FAA7"
client_secret_id: "fb7a6aac-48f7-4bff-ba65-f73ffbb0d24e"
resource_url: "https%3A%2F%2Fmanagement.core.windows.net"
