---
azure_storage_conn_str: "DefaultEndpointsProtocol=https;AccountName=azsvkstore;AccountKey=yVi1Bj/Fd2nH8WbqbyU5ME2TB0akiHpp/0gel0cECmxbLKNUyINj1wCyE/lQQO6sn023UojI3wow+XUK/GRddw==;EndpointSuffix=core.windows.net"
container_name: "az-data"
restart_url: "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/restart?api-version=2021-02-01"